### Recommendations Engine Testing
This uses the pre-trained model that is based from the latest `courses.csv` and `course_interactions.csv` datasets which are all based on the course explorer website.

In [4]:
from typing import Dict, Text

import numpy as np
import tensorflow as tf

import tensorflow_datasets as tfds
import tensorflow_recommenders as tfrs
import pandas as pd

In [11]:
# Load the model
model = tf.keras.models.load_model('model')
model(np.array(['42']))

(<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
 array([[0.02580016, 0.02382596, 0.02304047, 0.02240089, 0.02215362,
         0.0216061 , 0.02036874, 0.0203048 , 0.01926893, 0.01847   ]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 10), dtype=string, numpy=
 array([[b'Emergency Medicine Courses \xe2\x80\x93 We provide free open online ...',
         b'BA (Hons) Graphic Design',
         b'Best Operating System Courses & Certifications [2023]',
         b'Best Data Mining Courses Online | Beginner \xe2\x86\x92 Advanced',
         b'Bachelor of Science in Architecture (BSARCH)',
         b'Artificial Intelligence Programs | Stanford OnlineArtificial Intelligence Professional Program - Stanford Online',
         b'521043S Internet of Things',
         b'Artificial Intelligence (AI) Online Training Courses',
         b'BSc (Hons) in Software Engineering',
         b'Object-oriented Programming in Python - Online Course']],
       dtype=object)>)